---
title: "R Assignment"
author: "Cynthia"
date: "2022-08-31"
output: html_document
---

# **Installing and Configuring Packages**

    install.packages("tidyverse") 
    library(tidyverse)
    library(datasets)   #Load the datasets package
    library(gapminder)   #Load the gapminder package 
    install.packages("gapminder")
    library("gapminder")
    attach(iris)   #Attach iris data to the R search path

# **R Challenges**

## Challenge 1: Use both filter() and select() to create a subset of data frame that contains sepal length of value more than 5, sepal width and species

    `iris_species <- iris %>% select(Sepal.Length, Sepal.Width, Species) %>% filter(Sepal.Length > 5)`

### *Notes*

-   `attach(iris)` loads the iris data set for use.

-   `iris_species` is the variable created.

-   `%>%` is used to create a pipe.

-   `select()` function is used to select variables of interest in data set.

-   `filter()` function is used to filter out specific qualities in a variable in a data set.

## Challenge 2: Use group_by(), summarize(), mean(), sd(), min(), max() to calculate the mean, standard deviation, get maximum value, minimum value of each Species' Sepal.Width

`mean_sepal_spec <- iris %>% group_by(Species) %>% summarise(mean_sepal_width = mean(Sepal.Width), sd_sepal_width = sd(Sepal.Width), min_sepal_width = min(Sepal.Width), max_sepal_width = max(Sepal.Width))`

### *Notes*

-   `group_by()` function groups data set to several data segments based on the variables in the data set; eg group_by(Species)

-   `summarise()` pools all the imposed data points to one; eg summarise(mean(), sd()) to one data set.

-   `mean()` calculates mean

-   `sd()` calculates standard deviation

-   `min()` calculates min no

-   `max()` calculates max no

## Challenge 3: Use group_by(), mutate(), summarize(), mean(), sd(), min(), max() to calculate the mean, sd, find maximum and minimum of a new column of variable called SPlength where the Sepal.Length is divided by Petal.Length

    `sp_length <- iris
    %>% group_by(Species) %>% mutate(SPlength = Sepal.Length/Petal.Length) %>% summarise(mean_SPlength = mean(SPlength), sd_SPlength = sd(SPlength), min_SPlength = min(SPlength), max_SPlength = max(SPlength))`

### *Notes*

-   `mutate()` Creates new variables of a data frame eg new column called 'SPlength' in the data set.

# **Extra Notes**

## Creating a ScatterPlot

### *scatter plot that compares petal width and length*

    `ggplot(iris_small, aes(x=Petal.Length, y=Petal.Width)) + geom_point()`

### *Adding color to the scatterplot*

    `ggplot(iris_small, aes(x=Petal.Length, y=Petal.Width, color=Species)) + geom_point()`

### *Using different size for different variable*

    `ggplot(iris_small, aes(x=Petal.Length, y=Petal.Width, color=Species, size=Sepal.Length)) + geom_point()`

### *Facesetting*

    `ggplot(iris_small, aes(x=Petal.Length, y=Petal.Width)) + geom_point()+ facet_wrap(~Species) `

## Creating a Line Plot

    `ggplot(by_year, aes(x=year, y=medianGdpPerCap))+ geom_line()+ expand_limits(y=0)` 

### *Creating a Bar Plot*

    `ggplot(by_species, aes(x=Species, y=medianPL)) + geom_col()`

### *Creating a Histogram*

    `ggplot(iris_small, aes(x=Petal.Length))+ geom_histogram()`
     

### *Creating a Box Plot*

    `ggplot(iris_small, aes(x=Species, y=Sepal.Width))+ geom_boxplot()`

-------------------------------------------------------------------------------------------------------------------------------------------------------

Adios!
